sudo: false
language: node_js
node_js:
  - '10.4.0
steps: 
  - run: 
    name: Install FOSSA
    command: curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | sudo bash
  - checkout
before_script:
  - cd app && fossa
